#!/usr/bin/env bash

DECOMPOSER_TARGET_DIR=${DECOMPOSER_TARGET_DIR:-/var/www/libs/}

CHANGELOG_FILE=${CWD}/decomposer.diffnotes.md
CHANGELOG_TIME="5 minutes ago"

parse_arguments() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      "-f" | "--file")
        if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
          case "$2" in
            /*) CHANGELOG_FILE="$2" ;;
            *) CHANGELOG_FILE="${CWD}/$2" ;;
          esac
          shift
        fi
        ;;
      "-t" | "--time")
        if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
          CHANGELOG_TIME="$2"
          shift
        fi
        ;;
      *)
        printf "Unknown option %s\n" "$1"
        if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
          shift
        fi
        ;;
    esac
    shift
  done
}

validate_arguments() {
  if ! [ -f "${CWD}/decomposer.json" ]; then
    exit_error 'No decomposer.json found.'
  fi

  # Clear changelog and test write
  if ! printf '' 2> /dev/null > "${CHANGELOG_FILE}"; then
    exit_error "Changelog file '${CHANGELOG_FILE}' is not writable."
  fi
}

process_file() {
  local file="$1"

  local project_name

  project_name=$(
    git config --get remote.origin.url \
      | sed -e 's|.*/\(.*\)|\1|' -e 's|\.git$||'
  )

  write_repo_changelog "${project_name}" "${CWD}"

  map_libraries_repo "${file}" write_repo_changelog
}

write_repo_changelog() (
  local name="$1"
  local repo="$2"

  local base_ref added removed

  cd "${repo}" || return 1

  base_ref=$(
    git rev-parse "HEAD@{${CHANGELOG_TIME}}" 2> /dev/null
  )

  added=$(
    git cherry -v "${base_ref}" HEAD \
      | cut -d " " -f 3-
  )
  removed=$(
    git cherry -v HEAD "${base_ref}" \
      | cut -d " " -f 3-
  )

  if [ -z "${added}" ] && [ -z "${removed}" ]; then
    return
  fi

  {
    printf "# %s:\n\n" "${name}"

    if [ -n "${added}" ]; then
      printf '## Added:\n%s\n\n' "${added}"
    fi

    if [ -n "${removed}" ]; then
      printf '## Removed:\n%s\n\n' "${removed}"
    fi
  } >> "${CHANGELOG_FILE}"
)

parse_arguments "$@"
validate_arguments

process_file "${CWD}/decomposer.json"
