decomposer(1)

# NAME

decomposer - Manage libraries for a PHP project

# SYNOPSIS

decomposer _command_ [_args_]

# DESCRIPTION

Decomposer is a tool to manage the libraries used in a PHP project.

# COMMANDS

_decomposer-validate_(1)
	Validate the decomposer.json file

_decomposer-install_(1)
	Install all the libraries

_decomposer-generate-changelog_(1)
	Generate a changelog of the main project and its libraries
