# SPDX-FileCopyrightText: Copyright 2025 Move Agency Group B.V., Zwolle, The Netherlands
# SPDX-License-Identifier: CC0-1.0

name: General Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  typos:
    runs-on: ubuntu-latest
    continue-on-error: false
    name: "Spellcheck (typos)"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: typos-action
        uses: crate-ci/typos@master
